module.exports = [
    "Belgium",
    "Bruxelles",
    "Antwerpen",
    "Gent",
    "Charleroi",
    "Liège",
    "Brugge",
    "Namur",
    "Leuven",
    "Mons",
    "Kortrijk",
    "Oostende",
    "Bulgaria",
    "Sofia",
    "Plovdiv",
    "Varna",
    "Burgas",
    "Pleven",
    "Ruse",
    "Vidin",
    "Stara Zagora",
    "Sliven",
    "Dobrich",
    "Shumen",
    "Pernik",
    "Yambol",
    "Haskovo",
    "Pazardzhik",
    "Blagoevgrad",
    "Veliko Tarnovo",
    "Vratsa",
    "Czech Republic",
    "Praha",
    "Brno",
    "Ostrava",
    "Plzen",
    "Ústí nad Labem",
    "Olomouc",
    "Liberec",
    "Ceské Budejovice",
    "Hradec Králové",
    "Pardubice",
    "Zlín",
    "Kladno",
    "Karlovy Vary",
    "Jihlava",
    "Havírov",
    "Most",
    "Karviná",
    "Chomutov-Jirkov",
    "Denmark",
    "København",
    "Århus",
    "Odense",
    "Aalborg",
    "Germany",
    "Berlin",
    "Hamburg",
    "München",
    "Köln",
    "Frankfurt am Main",
    "Essen",
    "Stuttgart",
    "Leipzig",
    "Dresden",
    "Dortmund",
    "Düsseldorf",
    "Bremen",
    "Hannover",
    "Nürnberg",
    "Bochum",
    "Bielefeld",
    "Halle an der Saale",
    "Magdeburg",
    "Wiesbaden",
    "Göttingen",
    "Mülheim a.d.Ruhr",
    "Moers",
    "Darmstadt",
    "Trier",
    "Freiburg im Breisgau",
    "Regensburg",
    "Frankfurt",
    "Weimar",
    "Schwerin",
    "Erfurt",
    "Augsburg",
    "Bonn",
    "Karlsruhe",
    "Mönchengladbach",
    "Mainz",
    "Kiel",
    "Saarbrücken",
    "Potsdam",
    "Koblenz",
    "Rostock",
    "Kaiserslautern",
    "Iserlohn",
    "Esslingen am Neckar",
    "Hanau",
    "Wilhelmshaven",
    "Ludwigsburg",
    "Tübingen",
    "Villingen-Schwenningen",
    "Flensburg",
    "Marburg",
    "Konstanz",
    "Neumünster",
    "Brandenburg an der Havel",
    "Gießen",
    "Lüneburg",
    "Bayreuth",
    "Celle",
    "Aschaffenburg",
    "Bamberg",
    "Plauen",
    "Neubrandenburg",
    "Fulda",
    "Kempten",
    "Landshut",
    "Sindelfingen",
    "Rosenheim",
    "Frankenthal",
    "Stralsund",
    "Friedrichshafen",
    "Offenburg",
    "Görlitz",
    "Sankt Augustin",
    "Neu-Ulm",
    "Schweinfurt",
    "Greifswald",
    "Wetzlar",
    "Speyer",
    "Passau",
    "Dessau-Roßlau",
    "Duisburg",
    "Mannheim",
    "Gelsenkirchen",
    "Münster",
    "Chemnitz",
    "Braunschweig",
    "Aachen",
    "Krefeld",
    "Oberhausen",
    "Lübeck",
    "Hagen",
    "Kassel",
    "Hamm",
    "Herne",
    "Solingen",
    "Osnabrück",
    "Ludwigshafen am Rhein",
    "Leverkusen",
    "Oldenburg",
    "Neuss",
    "Heidelberg",
    "Paderborn",
    "Würzburg",
    "Recklinghausen",
    "Wolfsburg",
    "Bremerhaven",
    "Bottrop",
    "Heilbronn",
    "Remscheid",
    "Offenbach am Main",
    "Ulm",
    "Pforzheim",
    "Ingolstadt",
    "Gera",
    "Salzgitter",
    "Reutlingen",
    "Fürth",
    "Cottbus",
    "Siegen",
    "Bergisch Gladbach",
    "Hildesheim",
    "Witten",
    "Zwickau",
    "Erlangen",
    "Wuppertal",
    "Jena",
    "Düren",
    "Bocholt",
    "Estonia",
    "Tallinn",
    "Tartu",
    "Narva",
    "Ireland",
    "Dublin",
    "Cork",
    "Limerick",
    "Galway",
    "Waterford",
    "Greece",
    "Athina",
    "Thessaloniki",
    "Pátra",
    "Irakleio",
    "Larisa",
    "Volos",
    "Ioannina",
    "Kavala",
    "Kalamata",
    "Spain",
    "Madrid",
    "Barcelona",
    "Valencia",
    "Sevilla",
    "Zaragoza",
    "Málaga",
    "Murcia",
    "Las Palmas",
    "Valladolid",
    "Palma de Mallorca",
    "Santiago de Compostela",
    "Vitoria",
    "Oviedo",
    "Pamplona",
    "Santander",
    "Toledo",
    "Badajoz",
    "Logroño",
    "Bilbao",
    "Córdoba",
    "Alicante",
    "Vigo",
    "Gijón",
    "L'Hospitalet de Llobregat",
    "Santa Cruz de Tenerife",
    "A Coruña",
    "Barakaldo",
    "Reus",
    "Telde",
    "Parla",
    "Lugo",
    "San Fernando",
    "Girona",
    "Cáceres",
    "Torrevieja",
    "Pozuelo de Alarcón",
    "Puerto de Santa María",
    "Coslada",
    "Avilés",
    "Talavera de la Reina",
    "Palencia",
    "Sant Boi de Llobregat",
    "Ferrol",
    "Pontevedra",
    "Ceuta",
    "Gandia",
    "Rozas de Madrid",
    "Guadalajara",
    "Sant Cugat del Vallès",
    "Manresa",
    "Getxo",
    "Rubí",
    "Ciudad Real",
    "Benidorm",
    "Melilla",
    "Viladecans",
    "Ponferrada",
    "San Sebastián de los Reyes",
    "Zamora",
    "Fuengirola",
    "Cerdanyola del Vallès",
    "Sanlúcar de Barrameda",
    "Vilanova i la Geltrú",
    "Prat de Llobregat",
    "Línea de la Concepción",
    "Cornellà de Llobregat",
    "Majadahonda",
    "Torremolinos",
    "Castelldefels",
    "Irun",
    "Granollers",
    "Arrecife",
    "Elda",
    "Santa Lucía de Tirajana",
    "Mollet del Vallès",
    "Granada",
    "Badalona",
    "Móstoles",
    "Elche",
    "Cartagena",
    "Sabadell",
    "Jerez de la Frontera",
    "Fuenlabrada",
    "San Sebastián",
    "Alcalá de Henares",
    "Terrassa",
    "Leganés",
    "Almería",
    "Burgos",
    "Salamanca",
    "Alcorcón",
    "Getafe",
    "Albacete",
    "Castellón de la Plana",
    "Huelva",
    "Cádiz",
    "León",
    "San Cristóbal de la Laguna",
    "Tarragona",
    "Santa Coloma de Gramenet",
    "Jaén",
    "Lleida",
    "Ourense",
    "Mataró",
    "Dos Hermanas",
    "Algeciras",
    "Marbella",
    "Torrejón de Ardoz",
    "Alcobendas",
    "Alcalá de Guadaíra",
    "Alcoy",
    "Ávila",
    "Benalmádena",
    "Chiclana de la Frontera",
    "Collado Villalba",
    "Cuenca",
    "Eivissa",
    "Linares",
    "Lorca",
    "Mérida",
    "Sagunto",
    "Torrelavega",
    "Valdemoro",
    "Puerto de la Cruz",
    "Paterna",
    "Igualada",
    "Torrent",
    "Mislata",
    "Rivas-Vaciamadrid",
    "Santurtzi",
    "Esplugues de Llobregat",
    "San Vicente del Raspeig",
    "France",
    "Paris",
    "Lyon",
    "Toulouse",
    "Strasbourg",
    "Bordeaux",
    "Nantes",
    "Lille",
    "Montpellier",
    "Saint-Etienne",
    "Le Havre",
    "Rennes",
    "Amiens",
    "Nancy",
    "Metz",
    "Reims",
    "Orléans",
    "Dijon",
    "Poitiers",
    "Clermont-Ferrand",
    "Caen",
    "Limoges",
    "Besançon",
    "Grenoble",
    "Ajaccio",
    "Saint Denis",
    "Fort-de-France",
    "Toulon",
    "Valenciennes",
    "Tours",
    "Angers",
    "Brest",
    "Le Mans",
    "Avignon",
    "Mulhouse",
    "Dunkerque",
    "Perpignan",
    "Nîmes",
    "Pau",
    "Bayonne",
    "Annemasse",
    "Annecy",
    "Lorient",
    "Montbéliard",
    "Troyes",
    "Saint-Nazaire",
    "La Rochelle",
    "Angoulême",
    "Boulogne-sur-Mer",
    "Chambéry",
    "Chalon-sur-Saône",
    "Chartres",
    "Niort",
    "Calais",
    "Béziers",
    "Arras",
    "Bourges",
    "Saint-Brieuc",
    "Quimper",
    "Vannes",
    "Cherbourg",
    "Tarbes",
    "Compiègne",
    "Belfort",
    "Roanne",
    "Saint-Quentin",
    "Beauvais",
    "Creil",
    "Evreux",
    "Châteauroux",
    "Brive-la-Gaillarde",
    "Albi",
    "Fréjus",
    "Châlons-en-Champagne",
    "Aubagne",
    "Aix-en-Provence",
    "Marseille",
    "Nice",
    //"CA de Sophia-Antipolis",
    "Lens - Liévin",
    "Hénin - Carvin",
    "Douai",
    "Marne la Vallée",
    "Versailles",
    "Communauté d'Agglomération Saint Germain Boucles de Seine",
    "Sénart en Essonne",
    "Valence",
    "Rouen",
    //"Communauté de communes de Marne et Chantereine",
    //"Communauté d'Agglomération des deux Rives de la Seine",
    //"Communauté d'Agglomération des Coteaux de la Seine",
    "Essonne",
    //"Communauté d'Agglomération Brie Francilienne",
    "Communauté d'Agglomération les Portes de l'Essonne",
    "Val et Forêt",
    "Communauté de communes de l'Ouest de la Plaine de France",
    "Communauté d'Agglomération le Parisis",
    "Melun",
    "Meaux",
    "Mantes en Yvelines",
    "Evry",
    "Communauté d'Agglomération du Plateau de Saclay",
    //"Communauté d'Agglomération de Seine Essonne",
    "Communauté d'Agglomération du Val d'Orge",
    //"Communauté d'Agglomération du Val d'Yerres",
    "Communauté d'Agglomération Sénart - Val de Seine",
    "Communauté d'Agglomération Val de France",
    "Communauté d'Agglomération de la Vallée de Montmorency",
    "Martigues",
    "Argenteuil - Bezons",
    "Cergy-Pontoise",
    "Charleville-Mézières",
    "Colmar",
    "Lacs de l'Essonne",
    "Saint-Quentin en Yvelines",
    "Cannes",
    "Zagreb",
    "Rijeka",
    "Slavonski Brod",
    "Osijek",
    "Split",
    "Pula - Pola",
    "Zadar",
    "Italy",
    "Roma",
    "Milano",
    "Napoli",
    "Torino",
    "Palermo",
    "Genova",
    "Firenze",
    "Bari",
    "Bologna",
    "Catania",
    "Venezia",
    "Verona",
    "Cremona",
    "Trento",
    "Trieste",
    "Perugia",
    "Ancona",
    "Pescara",
    "Campobasso",
    "Caserta",
    "Taranto",
    "Potenza",
    "Catanzaro",
    "Reggio di Calabria",
    "Sassari",
    "Cagliari",
    "Padova",
    "Brescia",
    "Modena",
    "Foggia",
    "Salerno",
    "Piacenza",
    "Bolzano",
    "Udine",
    "La Spezia",
    "Lecce",
    "Barletta",
    "Pesaro",
    "Como",
    "Pisa",
    "Treviso",
    "Varese",
    "Busto Arsizio",
    "Asti",
    "Pavia",
    "Massa",
    "Cosenza",
    "Savona",
    "Matera",
    "Acireale",
    "Avellino",
    "Pordenone",
    "Lecco",
    "Altamura",
    "Bitonto",
    "Molfetta",
    "Battipaglia",
    "Bisceglie",
    "Carpi",
    "Cerignola",
    "Gallarate",
    "Gela",
    "Saronno",
    "Bagheria",
    "Anzio",
    "Sassuolo",
    "Messina",
    "Prato",
    "Parma",
    "Livorno",
    "Reggio nell'Emilia",
    "Ravenna",
    "Ferrara",
    "Rimini",
    "Siracusa",
    "Monza",
    "Bergamo",
    "Forlì",
    "Latina",
    "Vicenza",
    "Terni",
    "Novara",
    "Giugliano in Campania",
    "Alessandria",
    "Arezzo",
    "Grosseto",
    "Brindisi",
    "Trapani",
    "Ragusa",
    "Andria",
    "Trani",
    "L'Aquila",
    "Cyprus",
    "Lefkosia",
    "Lemesos",
    "Latvia",
    "Riga",
    "Liepaja",
    "Jelgava",
    "Daugavpils",
    "Lithuania",
    "Vilnius",
    "Kaunas",
    "Panevezys",
    "Alytus",
    "Klaipeda",
    "Siauliai",
    "Luxembourg",
    "Hungary",
    "Budapest",
    "Miskolc",
    "Nyíregyháza",
    "Pécs",
    "Debrecen",
    "Szeged",
    "Gyõr",
    "Kecskemét",
    "Székesfehérvár",
    "Szombathely",
    "Szolnok",
    "Tatabánya",
    "Veszprém",
    "Békéscsaba",
    "Kaposvár",
    "Eger",
    "Dunaújváros",
    "Zalaegerszeg",
    "Sopron",
    "Malta",
    "Valletta",
    "Netherlands",
    "'s-Gravenhage",
    "Amsterdam",
    "Rotterdam",
    "Utrecht",
    "Eindhoven",
    "Tilburg",
    "Groningen",
    "Enschede",
    "Arnhem",
    "Heerlen",
    "Almere",
    "Breda",
    "Nijmegen",
    "Apeldoorn",
    "Leeuwarden",
    "Sittard-Geleen",
    "Hilversum",
    "Roosendaal",
    "Nissewaard",
    "Purmerend",
    "Alphen aan den Rijn",
    "Bergen op Zoom",
    "Gouda",
    "Hoorn",
    "Middelburg",
    "Haarlem",
    "Zaanstad",
    "'s-Hertogenbosch",
    "Amersfoort",
    "Maastricht",
    "Leiden",
    "Haarlemmermeer",
    "Zoetermeer",
    "Zwolle",
    "Ede",
    "Deventer",
    "Alkmaar",
    "Venlo",
    "Helmond",
    "Hengelo",
    "Almelo",
    "Lelystad",
    "Oss",
    "Assen",
    "Veenendaal",
    "Heemskerk",
    "Soest",
    "Austria",
    "Wien",
    "Graz",
    "Linz",
    "Salzburg",
    "Innsbruck",
    "Klagenfurt",
    "Poland",
    "Warszawa",
    "Lódz",
    "Kraków",
    "Wroclaw",
    "Poznan",
    "Gdansk",
    "Szczecin",
    "Bydgoszcz",
    "Lublin",
    "Katowice",
    //"Górnoslaski Zwiazek Metropolitalny",
    "Bialystok",
    "Kielce",
    "Torun",
    "Olsztyn",
    "Rzeszów",
    "Opole",
    "Gorzów Wielkopolski",
    "Zielona Góra",
    "Jelenia Góra",
    "Nowy Sacz",
    "Suwalki",
    "Konin",
    "Zory",
    "Czestochowa",
    "Radom",
    "Plock",
    "Kalisz",
    "Koszalin",
    "Slupsk",
    "Jastrzebie-Zdrój",
    "Siedlce",
    "Piotrków Trybunalski",
    "Lubin",
    "Pila",
    "Inowroclaw",
    "Ostrowiec Swietokrzyski",
    "Gniezno",
    "Stargard Szczecinski",
    "Ostrów Wielkopolski",
    "Przemysl",
    "Zamosc",
    "Chelm",
    "Pabianice",
    "Glogów",
    "Stalowa Wola",
    "Tomaszów Mazowiecki",
    "Lomza",
    "Leszno",
    "Swidnica",
    "Zgierz",
    "Tczew",
    "Elk",
    "Gdynia",
    "Sosnowiec",
    "Gliwice",
    "Zabrze",
    "Bytom",
    "Bielsko-Biala",
    "Ruda Slaska",
    "Rybnik",
    "Tychy",
    "Walbrzych",
    "Elblag",
    "Wloclawek",
    "Tarnów",
    "Chorzów",
    "Legnica",
    "Grudziadz",
    "Portugal",
    "Lisboa",
    "Porto",
    "Braga",
    "Funchal",
    "Coimbra",
    "Setúbal",
    "Ponta Delgada",
    "Aveiro",
    "Faro",
    "Seixal",
    "Amadora",
    "Almada",
    "Odivelas",
    "Viseu",
    "Valongo",
    "Viana do Castelo",
    "Paredes",
    "Barreiro",
    "Póvoa de Varzim",
    "Sintra",
    "Vila Nova de Gaia",
    "Matosinhos",
    "Gondomar",
    "Guimarães",
    "Vila Franca de Xira",
    "Romania",
    "Bucuresti",
    "Cluj-Napoca",
    "Timisoara",
    "Craiova",
    "Braila",
    "Oradea",
    "Bacau",
    "Arad",
    "Sibiu",
    "Târgu Mures",
    "Piatra Neamt",
    "Calarasi",
    "Giurgiu",
    "Alba Iulia",
    "Focsani",
    "Târgu Jiu",
    "Tulcea",
    "Târgoviste",
    "Slatina",
    "Bârlad",
    "Roman",
    "Bistrita",
    "Constanta",
    "Iasi",
    "Galati",
    "Brasov",
    "Ploiesti",
    "Pitesti",
    "Baia Mare",
    "Buzau",
    "Satu Mare",
    "Botosani",
    "Râmnicu Vâlcea",
    "Suceava",
    "Drobeta-Turnu Severin",
    "Slovenia",
    "Ljubljana",
    "Maribor",
    "Slovakia",
    "Bratislava",
    "Kosice",
    "Banská Bystrica",
    "Nitra",
    "Presov",
    "Zilina",
    "Trnava",
    "Trencín",
    "Finland",
    "Helsinki",
    "Tampere",
    "Turku",
    "Oulu",
    "Espoo",
    "Vantaa",
    "Lahti",
    "Kuopio",
    "Jyväskylä",
    "Sweden",
    "Stockholm",
    "Göteborg",
    "Malmö",
    "Jönköping",
    "Umeå",
    "Uppsala",
    "Linköping",
    "Örebro",
    "Västerås",
    "Norrköping",
    "Helsingborg",
    "Lund",
    "Borås",
    "United Kingdom",
    "Birmingham",
    "West Midlands",
    "Leeds",
    "Glasgow City",
    "Glasgow",
    "Bradford",
    "Liverpool",
    "City of Edinburgh",
    "Manchester",
    "Cardiff",
    "Sheffield",
    "Bristol",
    "Belfast",
    "Newcastle upon Tyne",
    //"Tyneside conurbation",
    "Leicester",
    "Aberdeen City",
    "Cambridge",
    "Exeter",
    "Lincoln",
    "Gravesham",
    "Stevenage",
    "Wrexham",
    "Portsmouth",
    "Worcester",
    "Coventry",
    "Kingston-upon-Hull",
    "Stoke-on-trent",
    "Wolverhampton",
    "Nottingham",
    "Wirral",
    "Bath and North East Somerset",
    "Thurrock",
    "Guildford",
    "Thanet",
    "Nuneaton and Bedworth",
    "Waveney",
    "Tunbridge Wells",
    "Ashford",
    "East Staffordshire",
    "Darlington",
    "Worthing",
    "Mansfield",
    "Chesterfield",
    "Burnley",
    "Great Yarmouth",
    "Woking",
    "Hartlepool",
    "Cannock Chase",
    "Eastbourne",
    "Hastings",
    "Hyndburn",
    "Redditch",
    "Tamworth",
    "Harlow",
    "Halton",
    "City of London",
    "Barking and Dagenham",
    "Barnet",
    "Bexley",
    "Brent",
    "Bromley",
    "Camden",
    "Croydon",
    "Ealing",
    "Enfield",
    "Greenwich",
    "Hackney",
    "Hammersmith and Fulham",
    "Haringey",
    "Harrow",
    "Havering",
    "Hillingdon",
    "Hounslow",
    "Islington",
    "Kensington and Chelsea",
    "Kingston upon Thames",
    "Lambeth",
    "Lewisham",
    "Merton",
    "Newham",
    "Redbridge",
    "Richmond upon Thames",
    "Southwark",
    "Sutton",
    "Tower Hamlets",
    "Waltham Forest",
    "Wandsworth",
    "Westminster",
    "Kirklees",
    "North Lanarkshire",
    "Wakefield",
    "Dudley",
    "Wigan",
    "Doncaster",
    "Stockport",
    "Sefton",
    "Sandwell",
    "Sunderland",
    "Bolton",
    "Walsall",
    "Medway",
    "Rotherham",
    "Brighton and Hove",
    "Plymouth",
    "Swansea",
    "Derby",
    "Barnsley",
    "Southampton",
    "Oldham",
    "Salford",
    "Tameside",
    "Trafford",
    "Milton Keynes",
    "Rochdale",
    "Solihull",
    "Northampton",
    "North Tyneside",
    "Gateshead",
    "Warrington",
    "Luton",
    "York",
    "Bury",
    "Swindon",
    "Stockton-on-Tees",
    "St. Helens",
    "Basildon",
    "Bournemouth",
    "Wycombe",
    "Southend-on-Sea",
    "Telford and Wrekin",
    "North East Lincolnshire",
    "Chelmsford",
    "Peterborough",
    "Colchester",
    "South Tyneside",
    "Basingstoke and Deane",
    "Bedford",
    "Dundee City",
    "Falkirk",
    "Reading",
    "Blackpool",
    "Maidstone",
    "Poole",
    "Dacorum",
    "Blackburn with Darwen",
    "Newport",
    "Middlesbrough",
    "Oxford",
    "Torbay",
    "Preston",
    "St Albans",
    "Warwick",
    "Newcastle-under-Lyme",
    "Norwich",
    "Slough",
    "Cheshire West and Chester",
    "Ipswich",
    "Cheltenham",
    "Gloucester",
    "Bracknell Forest",
    "Carlisle",
    "Crawley",
    "Watford",
    "Gosport",
    "Eastleigh",
    "Rushmoor",
    "Rugby",
    "Corby",
    "Kettering",
    "Inverclyde",
    "Renfrewshire",
    "Derry & Strabane",
    "Turkey",
    "Ankara",
    "Adana",
    "Antalya",
    "Balikesir",
    "Bursa",
    "Denizli",
    "Diyarbakir",
    "Edirne",
    "Erzurum",
    "Gaziantep",
    "Hatay",
    "Istanbul",
    "Izmir",
    "Kars",
    "Kastamonu",
    "Kayseri",
    "Kocaeli",
    "Konya",
    "Malatya",
    "Manisa",
    "Nevsehir",
    "Samsun",
    "Siirt",
    "Trabzon",
    "Van",
    "Zonguldak",
    "Norge",
    "Oslo",
    "Bergen",
    "Trondheim",
    "Stavanger",
    "Kristiansand",
    "Tromsø",
    "Schweiz",
    "Zürich",
    "Genève",
    "Basel",
    "Bern",
    "Lausanne",
    "Winterthur",
    "St. Gallen",
    "Luzern",
    "Lugano",
    "Biel"
]